name: Deploy experimental branches to devint bucket

on:
  push:
    branches:
      - experimental/*
      - feature/*

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: frontend-react-production-09041970
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19
      - name: build site
        run: |
          cd app
          npm install react-bootstrap bootstrap
          npm ci
          npm run build
      - name: deploy files to bucket
        run: | 
          cd app
          aws s3 cp build s3://${{ env.BUCKET_NAME }} --recursive --acl public-read
